[tool.poetry]
name = "{{cookiecutter.__project_slug}}"
version = "0.1.0"
description = "{{cookiecutter.project_description}}"
authors = ["{{cookiecutter.__author}}"]
license = "{{cookiecutter.license}}"
readme = "README.md"
include = ["README.md", "src/{{cookiecutter.__project_slug}}/schema", "project"]

[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = "^1.4"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry.dev-dependencies]
cruft = "^2.12"
linkml = "^1.4"
mkdocs-material = "^9.0"
mkdocs-mermaid2-plugin = "^0.6"
schemasheets = "^0.1"

[build-system]
requires = ["poetry-core>=1.5.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.extras]
docs = ["linkml", "mkdocs-material"]
