# Built from:
# https://docs.github.com/en/actions/guides/building-and-testing-python
---
name: Build and test {{cookiecutter.__project_slug}}

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}

      - name: Install Poetry
        run: |
          # run pip config here if required
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          python3 -m pipx install poetry

      - name: Install dependencies
        run: |
          ${HOME}/.local/bin/poetry lock
          ${HOME}/.local/bin/poetry install --no-interaction --no-root

      - name: Install project
        run: ${HOME}/.local/bin/poetry install --no-interaction

      - name: Run Linters
        run: |
          ${HOME}/.local/bin/poetry run linkml-lint src/{{cookiecutter.__project_slug}}/schema/{{cookiecutter.__project_slug}}.yaml --ignore-warnings

      - name: Run test suite
        run: |
          export PATH="${PATH}:${HOME}/.local/bin"
          poetry add requests[security]
          make test

